"""Add quantity to Fruit model

Revision ID: 39b5b7dfa810
Revises: 
Create Date: 2024-06-21 16:59:03.039810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '39b5b7dfa810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fruit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fruit', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###

