name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Adjust to your Python version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust if your requirements file has a different path

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust to your Node.js version

    - name: Install Node dependencies
      run: |
        cd frontend  # Change to your React app directory
        npm install

    - name: Build React app
      run: |
        cd frontend  # Change to your React app directory
        npm run build  # Make sure this script exists in your package.json

    - name: Transfer build to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        source: |
          ./frontend/build/*
          ./backend/*  # Adjust these paths to include all necessary files for your backend
        target: "/var/www/html"  # Ensure this directory is set up to serve via your Flask app

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo systemctl restart myflaskapp.service  # Adjust this command to your specific service restart command
